name: Continuos Integration

on: pull_request

jobs:
  continuos-integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Using node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.
      - name: run install, test:silent and test:coverage
        run: |
          npm install
          npm run test:silent
          npm run test:coverage
