name: Continuos Integration

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  continuos-integration:
    permissions:
      checks: write
      pull-requests: write
      contents: write

    runs-on: ubuntu-latest
    strategy:
      matrix:
        domain: [classes, services]

    outputs:
      classes: ${{ steps.outputs.classes }}
      services: ${{ steps.outputs.servives }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Instalando as dependencias
        run: npm install

      - name: Test with coverage
        run: npm run test $TEST_PATH -- --config --ci --json --collectCoverageFrom=$COVERAGE_TEST --coverage --testLocationInResults --outputFile=report.json
        continue-on-error: true
        env:
          CURRENT_DOMAIN: ${{ matrix.domain }}
          TEST_PATH: ${{ matrix.domain == 'src\/(?!domain)' || 'src/domain/$CURRENT_DOMAIN' }}
          COVERAGE_TEST: ${{ matrix.domain == 'src/!(domain)/**/*.ts(x)?' || 'src/domain/$CURRENT_DOMAIN/**/*.ts(x)?' }}
      # - uses: ArtiomTr/jest-coverage-report-action@v2.2.4
      #   with:
      #     working-directory: services
      #     test-script: npm run test:coverage
