name: Continuos Integration

on:
    pull_request_target:
      branch:
        - main

jobs:
  continuos-integration:
    permissions:
      checks: write
      pull-requests: write
      contents: write
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: ArtiomTr/jest-coverage-report-action@v2.2.4
        with:
          test-script: npm run test:coverage
          working-directory: services
          coverage-file: ./coverage/coverage-final.json
          base-coverage-file: ./coverage/main/coverage-final.json

