name: Continuos Integration

on:
   pull_request_target:
        branches:
            - main

jobs:
  continuos-integration:
    permissions:
      checks: write
      pull-requests: write
      contents: write
    name: Coverage
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Using node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.
      - name: Install Package
        run: |
          npm install --save-dev @commitlint/{cli,config-conventional}
          npm install --save-dev jest

      # - name: Rodar os testes unitarios
      #   run: |
      #     npm run test

      - name: Coletar os coverage do teste
        run: |
          npm run test:coverage
      - uses: marocchino/sticky-pull-request-comment@v2
          with:
            path: ./coverage/coverage-final.json
      # - uses: ArtiomTr/jest-coverage-report-action@v2
      #     id: coverage
      #     with:
      #       test-script: npm run test:silent
      #       output: report-markdown
            # github-token: ${{ secrets.GITHUB_TOKEN}}
      # - uses: marocchino/sticky-pull-request-comment@v2
      #     with:
      #       message: ${{ steps.coverage.outputs.report }}

